spring:
  datasource:
    url: jdbc:mysql://commerce-database.cd2aggce80z8.ap-northeast-2.rds.amazonaws.com:3306/commerce
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect


app:
  add-test-products: true
  add-test-memberships: true

portone:
  api:
    base-url: https://api.portone.io
    secret: ${PORTONE_API_SECRET}
  webhook:
    secret: ${PORTONE_WEBHOOK_SECRET}
  store:
    id: store-7d77a131-55ec-4545-a6da-8799245cd4c9
  channel:
    kg-inicis: ${PORTONE_KG_CHANNEL_KEY}
    toss: ${PORTONE_TOSS_CHANNEL_KEY}

